os:
  - linux
  - osx
language: perl6
perl6:
  - 2020.08.2
  - latest
install:
  - rakudobrew build zef
  - zef install --deps-only --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
